version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: knowmydb_postgres
    environment:
      POSTGRES_DB: knowmydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit:
    build: .
    container_name: knowmydb_app
    ports:
      - "8501:8501"
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASS=postgres
      - PG_DB=knowmydb
      - OPENAI_API_KEY=sk-proj-1234567890
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: 